#ifndef EBPF_INST_H_
#define EBPF_INST_H_

struct ebpf_inst {
  uint8_t opcode;
  uint8_t dst : 4;
  uint8_t src : 4;
  int16_t offset;
  int32_t imm;
};

/* Class */
#define EBPF_CLASS_LD    0x00
#define EBPF_CLASS_LDX   0x01
#define EBPF_CLASS_ST    0x02
#define EBPF_CLASS_STX   0x03
#define EBPF_CLASS_ALU   0x04
#define EBPF_CLASS_JMP   0x05
#define EBPF_CLASS_ALU64 0x07

/* ALU/JMP */
#define EBPF_OP(code) ((code)&0xf0)
#define EBPF_SRC_IMM  0x00
#define EBPF_SRC_REG  0x08
#define EBPF_TO_LE    0x00
#define EBPF_TO_BE    0x08

/* ALU field */
#define EBPF_OPCODE_ADD  0x00
#define EBPF_OPCODE_SUB  0x10
#define EBPF_OPCODE_MUL  0x20
#define EBPF_OPCODE_DIV  0x30
#define EBPF_OPCODE_OR   0x40
#define EBPF_OPCODE_AND  0x50
#define EBPF_OPCODE_LSH  0x60
#define EBPF_OPCODE_RSH  0x70
#define EBPF_OPCODE_NEG  0x80
#define EBPF_OPCODE_MOD  0x90
#define EBPF_OPCODE_XOR  0xa0
#define EBPF_OPCODE_MOV  0xb0
#define EBPF_OPCODE_ARSH 0xc0 /* >> */
#define EBPF_OPCODE_END  0xd0

#define EBPF_OP_ADD_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_ADD)
#define EBPF_OP_ADD_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_ADD)
#define EBPF_OP_SUB_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_SUB)
#define EBPF_OP_SUB_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_SUB)
#define EBPF_OP_MUL_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_MUL)
#define EBPF_OP_MUL_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_MUL)
#define EBPF_OP_DIV_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_DIV)
#define EBPF_OP_DIV_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_DIV)
#define EBPF_OP_OR_IMM   (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_OR)
#define EBPF_OP_OR_REG   (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_OR)
#define EBPF_OP_AND_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_AND)
#define EBPF_OP_AND_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_AND)
#define EBPF_OP_LSH_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_LSH)
#define EBPF_OP_LSH_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_LSH)
#define EBPF_OP_RSH_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_RSH)
#define EBPF_OP_RSH_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_RSH)
#define EBPF_OP_NEG      (EBPF_CLASS_ALU | EBPF_OPCODE_NEG)
#define EBPF_OP_MOD_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_MOD)
#define EBPF_OP_MOD_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_MOD)
#define EBPF_OP_XOR_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_XOR)
#define EBPF_OP_XOR_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_XOR)
#define EBPF_OP_MOV_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_MOV)
#define EBPF_OP_MOV_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_MOV)
#define EBPF_OP_ARSH_IMM (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OPCODE_ARSH)
#define EBPF_OP_ARSH_REG (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OPCODE_ARSH)
#define EBPF_OP_LE       (EBPF_CLASS_ALU | EBPF_TO_LE | EBPF_OPCODE_END)
#define EBPF_OP_BE       (EBPF_CLASS_ALU | EBPF_TO_BE | EBPF_OPCODE_END)

/* ALU64 field */
#define EBPF_OP_ADD64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_ADD)
#define EBPF_OP_ADD64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_ADD)
#define EBPF_OP_SUB64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_SUB)
#define EBPF_OP_SUB64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_SUB)
#define EBPF_OP_MUL64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_MUL)
#define EBPF_OP_MUL64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_MUL)
#define EBPF_OP_DIV64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_DIV)
#define EBPF_OP_DIV64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_DIV)
#define EBPF_OP_OR64_IMM   (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_OR)
#define EBPF_OP_OR64_REG   (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_OR)
#define EBPF_OP_AND64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_AND)
#define EBPF_OP_AND64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_AND)
#define EBPF_OP_LSH64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_LSH)
#define EBPF_OP_LSH64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_LSH)
#define EBPF_OP_RSH64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_RSH)
#define EBPF_OP_RSH64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_RSH)
#define EBPF_OP_NEG64      (EBPF_CLASS_ALU64 | EBPF_OPCODE_NEG)
#define EBPF_OP_MOD64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_MOD)
#define EBPF_OP_MOD64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_MOD)
#define EBPF_OP_XOR64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_XOR)
#define EBPF_OP_XOR64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_XOR)
#define EBPF_OP_MOV64_IMM  (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_MOV)
#define EBPF_OP_MOV64_REG  (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_MOV)
#define EBPF_OP_ARSH64_IMM (EBPF_CLASS_ALU64 | EBPF_SRC_IMM | EBPF_OPCODE_ARSH)
#define EBPF_OP_ARSH64_REG (EBPF_CLASS_ALU64 | EBPF_SRC_REG | EBPF_OPCODE_ARSH)

/* JMP field */
#define EBPF_OPCODE_JA   0x00
#define EBPF_OPCODE_JEQ  0x10 /* == */
#define EBPF_OPCODE_JGT  0x20 /* > */
#define EBPF_OPCODE_JGE  0x30 /* >= */
#define EBPF_OPCODE_JSET 0x40 /* & */
#define EBPF_OPCODE_JNE  0x50 /* != */
#define EBPF_OPCODE_JSGT 0x60 /* signed > */
#define EBPF_OPCODE_JSGE 0x70 /* signed >= */
#define EBPF_OPCODE_CALL 0x80
#define EBPF_OPCODE_EXIT 0x90
#define EBPF_OPCODE_JLT  0xa0 /* < */
#define EBPF_OPCODE_JLE  0xb0 /* <= */
#define EBPF_OPCODE_JSLT 0xc0 /* signed < */
#define EBPF_OPCODE_JSLE 0xd0 /* siened <= */

#define EBPF_OP_JA       (EBPF_CLASS_JMP | EBPF_OPCODE__JA)
#define EBPF_OP_JEQ_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JEQ)
#define EBPF_OP_JEQ_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JEQ)
#define EBPF_OP_JGT_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JGT)
#define EBPF_OP_JGT_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JGT)
#define EBPF_OP_JGE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JGE)
#define EBPF_OP_JGE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JGE)
#define EBPF_OP_JSET_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JSET)
#define EBPF_OP_JSET_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JSET)
#define EBPF_OP_JNE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JNE)
#define EBPF_OP_JNE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JNE)
#define EBPF_OP_JSGT_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JSGT)
#define EBPF_OP_JSGT_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JSGT)
#define EBPF_OP_JSGE_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JSGE)
#define EBPF_OP_JSGE_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JSGE)
#define EBPF_OP_CALL     (EBPF_CLASS_JMP | EBPF_OPCODE_CALL)
#define EBPF_OP_EXIT     (EBPF_CLASS_JMP | EBPF_OPCODE_EXIT)
#define EBPF_OP_JLT_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JLT)
#define EBPF_OP_JLT_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JLT)
#define EBPF_OP_JLE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JLE)
#define EBPF_OP_JLE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JLE)
#define EBPF_OP_JSLT_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JSLT)
#define EBPF_OP_JSLT_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JSLT)
#define EBPF_OP_JSLE_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_OPCODE_JSLE)
#define EBPF_OP_JSLE_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_OPCODE_JSLE)

/* LD/LDX/ST/STX */
#define EBPF_MODE(code) ((code)&0xe0)
#define EBPF_SIZE(code) ((code)&0x18)

#define EBPF_SIZE_W  0x00
#define EBPF_SIZE_H  0x08
#define EBPF_SIZE_B  0x10
#define EBPF_SIZE_DW 0x18

#define EBPF_MODE_IMM  0x00
#define EBPF_MODE_ABS  0x20
#define EBPF_MODE_IND  0x40
#define EBPF_MODE_MEM  0x60
#define EBPF_MODE_XADD 0xc0

#define EBPF_OP_LDXW  (EBPF_CLASS_LDX | EBPF_MODE_MEM | EBPF_SIZE_W)
#define EBPF_OP_LDXH  (EBPF_CLASS_LDX | EBPF_MODE_MEM | EBPF_SIZE_H)
#define EBPF_OP_LDXB  (EBPF_CLASS_LDX | EBPF_MODE_MEM | EBPF_SIZE_B)
#define EBPF_OP_LDXDW (EBPF_CLASS_LDX | EBPF_MODE_MEM | EBPF_SIZE_DW)
#define EBPF_OP_STW   (EBPF_CLASS_ST | EBPF_MODE_MEM | EBPF_SIZE_W)
#define EBPF_OP_STH   (EBPF_CLASS_ST | EBPF_MODE_MEM | EBPF_SIZE_H)
#define EBPF_OP_STB   (EBPF_CLASS_ST | EBPF_MODE_MEM | EBPF_SIZE_B)
#define EBPF_OP_STDW  (EBPF_CLASS_ST | EBPF_MODE_MEM | EBPF_SIZE_DW)
#define EBPF_OP_STXW  (EBPF_CLASS_STX | EBPF_MODE_MEM | EBPF_SIZE_W)
#define EBPF_OP_STXH  (EBPF_CLASS_STX | EBPF_MODE_MEM | EBPF_SIZE_H)
#define EBPF_OP_STXB  (EBPF_CLASS_STX | EBPF_MODE_MEM | EBPF_SIZE_B)
#define EBPF_OP_STXDW (EBPF_CLASS_STX | EBPF_MODE_MEM | EBPF_SIZE_DW)
#define EBPF_OP_LDDW  (EBPF_CLASS_LD | EBPF_MODE_IMM | EBPF_SIZE_DW)

#endif // EBPF_INST_H_
