#ifndef EBPF_INST_H_
#define EBPF_INST_H_

struct ebpf_inst {
  uint8_t opcode;
  uint8_t dst : 4;
  uint8_t src : 4;
  int16_t offset;
  int32_t imm;
};

/* Class */
#define EBPF_CLASS_LD    0x00
#define EBPF_CLASS_LDX   0x01
#define EBPF_CLASS_ST    0x02
#define EBPF_CLASS_STX   0x03
#define EBPF_CLASS_ALU   0x04
#define EBPF_CLASS_JMP   0x05
#define EBPF_CLASS_ALU64 0x07

/* ALU field */
#define EBPF_OP(code) ((code)&0xf0)
#define EBPF_SRC_IMM  0x00
#define EBPF_SRC_REG  0x08
#define EBPF_TO_LE    0x00
#define EBPF_TO_BE    0x08

#define EBPF_ADD  0x00
#define EBPF_SUB  0x10
#define EBPF_MUL  0x20
#define EBPF_DIV  0x30
#define EBPF_OR   0x40
#define EBPF_AND  0x50
#define EBPF_LSH  0x60
#define EBPF_RSH  0x70
#define EBPF_NEG  0x80
#define EBPF_MOD  0x90
#define EBPF_XOR  0xa0
#define EBPF_MOV  0xb0
#define EBPF_ARSH 0xc0 /* >> */
#define EBPF_END  0xd0

#define EBPF_OP_ADD_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_ADD)
#define EBPF_OP_ADD_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_ADD)
#define EBPF_OP_SUB_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_SUB)
#define EBPF_OP_SUB_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_SUB)
#define EBPF_OP_MUL_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_MUL)
#define EBPF_OP_MUL_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_MUL)
#define EBPF_OP_DIV_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_DIV)
#define EBPF_OP_DIV_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_DIV)
#define EBPF_OP_OR_IMM   (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_OR)
#define EBPF_OP_OR_REG   (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_OR)
#define EBPF_OP_AND_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_AND)
#define EBPF_OP_AND_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_AND)
#define EBPF_OP_LSH_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_LSH)
#define EBPF_OP_LSH_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_LSH)
#define EBPF_OP_RSH_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_RSH)
#define EBPF_OP_RSH_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_RSH)
#define EBPF_OP_NEG      (EBPF_CLASS_ALU | EBPF_NEG)
#define EBPF_OP_MOD_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_MOD)
#define EBPF_OP_MOD_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_MOD)
#define EBPF_OP_XOR_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_XOR)
#define EBPF_OP_XOR_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_XOR)
#define EBPF_OP_MOV_IMM  (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_MOV)
#define EBPF_OP_MOV_REG  (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_MOV)
#define EBPF_OP_ARSH_IMM (EBPF_CLASS_ALU | EBPF_SRC_IMM | EBPF_ARSH)
#define EBPF_OP_ARSH_REG (EBPF_CLASS_ALU | EBPF_SRC_REG | EBPF_ARSH)
#define EBPF_OP_LE       (EBPF_CLASS_ALU | EBPF_TO_LE)
#define EBPF_OP_BE       (EBPF_CLASS_ALU | EBPF_TO_BE)

/* JMP field */
#define EBPF_JA   0x00
#define EBPF_JEQ  0x10 /* == */
#define EBPF_JGT  0x20 /* > */
#define EBPF_JGE  0x30 /* >= */
#define EBPF_JSET 0x40 /* & */
#define EBPF_JNE  0x50 /* != */
#define EBPF_JSGT 0x60 /* signed > */
#define EBPF_JSGE 0x70 /* signed >= */
#define EBPF_CALL 0x80
#define EBPF_EXIT 0x90
#define EBPF_JLT  0xa0 /* < */
#define EBPF_JLE  0xb0 /* <= */
#define EBPF_JSLT 0xc0 /* signed < */
#define EBPF_JSLE 0xd0 /* siened <= */

#define EBPF_OP_JA       (EBPF_CLASS_JMP | EBPF_JA)
#define EBPF_OP_JEQ_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JEQ)
#define EBPF_OP_JEQ_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JEQ)
#define EBPF_OP_JGT_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JGT)
#define EBPF_OP_JGT_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JGT)
#define EBPF_OP_JGE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JGE)
#define EBPF_OP_JGE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JGE)
#define EBPF_OP_JSET_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JSET)
#define EBPF_OP_JSET_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JSET)
#define EBPF_OP_JNE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JNE)
#define EBPF_OP_JNE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JNE)
#define EBPF_OP_JSGT_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JSGT)
#define EBPF_OP_JSGT_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JSGT)
#define EBPF_OP_JSGE_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JSGE)
#define EBPF_OP_JSGE_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JSGE)
#define EBPF_OP_CALL     (EBPF_CLASS_JMP | EBPF_CALL)
#define EBPF_OP_EXIT     (EBPF_CLASS_JMP | EBPF_EXIT)
#define EBPF_OP_JLT_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JLT)
#define EBPF_OP_JLT_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JLT)
#define EBPF_OP_JLE_IMM  (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JLE)
#define EBPF_OP_JLE_REG  (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JLE)
#define EBPF_OP_JSLT_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JSLT)
#define EBPF_OP_JSLT_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JSLT)
#define EBPF_OP_JSLE_IMM (EBPF_CLASS_JMP | EBPF_SRC_IMM | EBPF_JSLE)
#define EBPF_OP_JSLE_REG (EBPF_CLASS_JMP | EBPF_SRC_REG | EBPF_JSLE)

#endif // EBPF_INST_H_
